name: weather_buddy
description: "A weather app for the Philippines with CRUD functionality"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/icon/icon.png"
  adaptive_icon_background: "#42A5F5"
  adaptive_icon_foreground: "lib/icon/icon.png"
  web:
    generate: true
    image_path: "lib/icon/icon.png"
    background_color: "#42A5F5"
  windows:
    generate: true
    image_path: "lib/icon/icon.png"
  macos:
    generate: true
    image_path: "lib/icon/icon.png"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.9.0
  intl: ^0.19.0
  provider: ^6.1.1
  geolocator: ^10.1.0
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/icon/icon.png
    - .env

